/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Proyect.View;

import javax.swing.table.DefaultTableModel;
import Proyect.Model.ResumenDeGanancias;
import java.util.Arrays;

import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;
import java.util.Arrays;
import javax.swing.table.TableModel;
import Proyect.Model.Producto;
import javax.swing.JOptionPane;




/**
 *
 * @author pc
 */
public class FromResumenDeGanancias extends javax.swing.JInternalFrame {
    
    private DefaultTableModel dtm;
    private DefaultTableModel dtm2;
    private DefaultTableModel dtm3;
    
    private Object[] l = new Object[1];
    private Object[] p = new Object[3];
    private Object[] o = new Object[5];
    
    /**
     * Creates new form FromResumenDeGanancias
     */
    public FromResumenDeGanancias() {
        initComponents();
        

        setClosable(true);
        setResizable(true);
        setMaximizable(true);
        setIconifiable(true);
        
        
        dtm =(DefaultTableModel)jTable1.getModel();
        dtm2 =(DefaultTableModel)jTable4.getModel();
        dtm3 =(DefaultTableModel)jTable3.getModel();
        
        ResumenDeGanancias.agregarProductosDeHoyATabla(dtm);
        ResumenDeGanancias.agregarProductostablaTotal(dtm2);
        ResumenDeGanancias.agregarProductostablaUtilidadNeta(dtm3);
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        ganaciasPorDias = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Productos", "Cliente", "Cantidad", "Precio de compra", "Precio de venta", "Ingresos por productos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Utilidad neta(Ganancias)"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Total de ingresos"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        ganaciasPorDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ganancias de hoy", "Ganancias de cuatro días", "Ganancias de siete días", "Ganancias de quince días", "Ganancias de treinta días" }));
        ganaciasPorDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ganaciasPorDiasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ganaciasPorDias, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(6, 6, 6))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(ganaciasPorDias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(497, 497, 497))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ganaciasPorDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ganaciasPorDiasActionPerformed
        // TODO add your handling code here:
        String diasGanancia = ganaciasPorDias.getSelectedItem().toString();
        if(diasGanancia.equals("Ganancias de hoy")){
            for (int i = dtm.getRowCount() - 1; i >= 0; i--) {
                dtm.removeRow(i);
            }
            dtm2.removeRow(0);
            dtm3.removeRow(0);
            ResumenDeGanancias.agregarProductosDeHoyATabla(dtm);
            ResumenDeGanancias.agregarProductostablaTotal(dtm2);
            ResumenDeGanancias.agregarProductostablaUtilidadNeta(dtm3);          
        }
        
        else if(diasGanancia.equals("Ganancias de cuatro días")){
            for (int i = dtm.getRowCount() - 1; i >= 0; i--) {
                dtm.removeRow(i);
            }
            dtm2.removeRow(0);
            dtm3.removeRow(0);
            ResumenDeGanancias.agregarProductosDe4(dtm);
            ResumenDeGanancias.agregarProductostablaTotalDe4(dtm2);
            ResumenDeGanancias.agregarProductostablaUtilidadNetaDe4(dtm3);           
        }
        else if (diasGanancia.equals("Ganancias de siete días")){
            for (int i = dtm.getRowCount() - 1; i >= 0; i--) {
                dtm.removeRow(i);
            }
            dtm2.removeRow(0);
            dtm3.removeRow(0);
            ResumenDeGanancias.agregarProductosDe7(dtm);
            ResumenDeGanancias.agregarProductostablaTotalDe7(dtm2);
            ResumenDeGanancias.agregarProductostablaUtilidadNetaDe7(dtm3); 
            
        }
        else if (diasGanancia.equals("Ganancias de quince días")){
            for (int i = dtm.getRowCount() - 1; i >= 0; i--) {
                dtm.removeRow(i);
            }
            dtm2.removeRow(0);
            dtm3.removeRow(0);
            ResumenDeGanancias.agregarProductosDe15(dtm);
            ResumenDeGanancias.agregarProductostablaTotalDe15(dtm2);
            ResumenDeGanancias.agregarProductostablaUtilidadNetaDe15(dtm3); 
            
        }
        else if (diasGanancia.equals("Ganancias de treinta días")){
            for (int i = dtm.getRowCount() - 1; i >= 0; i--) {
                dtm.removeRow(i);
            }
            dtm2.removeRow(0);
            dtm3.removeRow(0);
            ResumenDeGanancias.agregarProductosDe30(dtm);
            ResumenDeGanancias.agregarProductostablaTotalDe30(dtm2);
            ResumenDeGanancias.agregarProductostablaUtilidadNetaDe30(dtm3); 
            
        }
        
        
    }//GEN-LAST:event_ganaciasPorDiasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ganaciasPorDias;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
