/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Proyect.View;

/**
 *
 * @author Samuel
 */


import Proyect.Model.MisDatosDeEjemplo;
import Proyect.View.FormInventario;
import Proyect.View.FormRutas;
import Proyect.View.FormHistoriaCompra;
import Proyect.View.FormProducto;
import Proyect.Model.Ruta;
import java.util.ArrayList;

public class Inicio extends javax.swing.JFrame {
    // === VARIABLES GLOBALES ===
    private FormInventario objFormInventario;
    private FormHistoriaCompra objFormHCompras;
    private javax.swing.JMenuItem menuItemRutaDelDia;
    private javax.swing.JInternalFrame jifFormRutas;
    private FormRutas objFormRutas;

    
    // === CONSTRUCTOR ===
    public Inicio() {
        initComponents(); // NetBeans GUI
        inicializarFormularios();
        inicializarMenuRutaDelDia();
    }

    // === INICIALIZA TUS FORMULARIOS ===
    private void inicializarFormularios() {
        // Inventario
        MisDatosDeEjemplo.crearProductos();
        
        objFormInventario = new FormInventario();
        jifFormInventario.setContentPane(objFormInventario);
        objFormInventario.setSize(700,500);
        jifFormInventario.setSize(700,500);
        jifFormInventario.setVisible(false);

        // Ruta del Día
        ArrayList<Ruta> rutas = MisDatosDeEjemplo.crearRutas(); 
        objFormRutas = new FormRutas(rutas);
        jifFormRutas = new javax.swing.JInternalFrame("Ruta del Día", true, true, true, true);
        jifFormRutas.setContentPane(objFormRutas);
        objFormRutas.setSize(700,500);
        jifFormRutas.setSize(700,500);
        jifFormRutas.setVisible(false);
        desktopPane.add(jifFormRutas);
        jifFormRutas.setBounds(10, 10, 700, 500);
        
        // Compras
        objFormHCompras = new FormHistoriaCompra();
        jifFormHCompras.setContentPane(objFormHCompras);
        objFormHCompras.setSize(700,500);
        jifFormHCompras.setSize(700,500);
        jifFormHCompras.setVisible(false);
        
    }

    // === AGREGA EL MENÚ Y SU ACCIÓN ===
    private void inicializarMenuRutaDelDia() {
    menuItemRutaDelDia = new javax.swing.JMenuItem("Ruta del Día");
    fileMenu.add(menuItemRutaDelDia);
    menuItemRutaDelDia.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jifFormRutas.setVisible(true);
            try {
                jifFormRutas.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {}
        }
    });
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jifFormInventario = new javax.swing.JInternalFrame();
        jifFormHCompras = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        InventarioMenuItem = new javax.swing.JMenuItem();
        salirMenuItem = new javax.swing.JMenuItem();
        Compras = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuItemNuevoProducto = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifFormInventario.setClosable(true);
        jifFormInventario.setVisible(false);

        javax.swing.GroupLayout jifFormInventarioLayout = new javax.swing.GroupLayout(jifFormInventario.getContentPane());
        jifFormInventario.getContentPane().setLayout(jifFormInventarioLayout);
        jifFormInventarioLayout.setHorizontalGroup(
            jifFormInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormInventarioLayout.setVerticalGroup(
            jifFormInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormInventario);
        jifFormInventario.setBounds(0, 0, 770, 510);
        jifFormInventario.getAccessibleContext().setAccessibleDescription("");

        jifFormHCompras.setClosable(true);
        jifFormHCompras.setIconifiable(true);
        jifFormHCompras.setMaximizable(true);
        jifFormHCompras.setVisible(true);

        javax.swing.GroupLayout jifFormHComprasLayout = new javax.swing.GroupLayout(jifFormHCompras.getContentPane());
        jifFormHCompras.getContentPane().setLayout(jifFormHComprasLayout);
        jifFormHComprasLayout.setHorizontalGroup(
            jifFormHComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormHComprasLayout.setVerticalGroup(
            jifFormHComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormHCompras);
        jifFormHCompras.setBounds(-10, -10, 550, 530);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        InventarioMenuItem.setMnemonic('o');
        InventarioMenuItem.setText("Inventario");
        InventarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventarioMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(InventarioMenuItem);

        salirMenuItem.setMnemonic('x');
        salirMenuItem.setText("Salir");
        salirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(salirMenuItem);

        Compras.setText("Compras");
        Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprasActionPerformed(evt);
            }
        });
        fileMenu.add(Compras);

        jMenuItem1.setText("Registrar pedido");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);

        menuItemNuevoProducto.setText("Nuevo producto");
        menuItemNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuevoProductoActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemNuevoProducto);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirMenuItemActionPerformed

    private void InventarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventarioMenuItemActionPerformed
        jifFormInventario.setVisible(true);
    }//GEN-LAST:event_InventarioMenuItemActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    private void ComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprasActionPerformed
        jifFormHCompras.setVisible(true);
    }//GEN-LAST:event_ComprasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormRegistrarPedido c = new FormRegistrarPedido();
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevoProductoActionPerformed
         FormProducto nuevoProducto = new FormProducto();
    nuevoProducto.setVisible(true);
    }//GEN-LAST:event_menuItemNuevoProductoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Compras;
    private javax.swing.JMenuItem InventarioMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JInternalFrame jifFormHCompras;
    private javax.swing.JInternalFrame jifFormInventario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemNuevoProducto;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem salirMenuItem;
    // End of variables declaration//GEN-END:variables

}
